name: FoodTracker
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "10.0"
targets:
  FoodTracker:
    type: application
    platform: iOS
    sources: [FoodTracker]
    settings:
      base:
        SWIFT_VERSION: 4.2
  FoodTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FoodTrackerTests
    dependencies:
      - target: FoodTracker
    settings:
      base:
        SWIFT_VERSION: 4.2
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FoodTracker.app/FoodTracker"
